version: "3.8"
services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80" # THIS IS IMPORTANT
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  laravel1:
    build:
      context: .
      dockerfile: ./docker/PHP/Dockerfile
    ports:
    - 9000:80
    volumes:
    - ./src:/var/www/html
    labels:
      - "traefik.http.routers.laravel1.rule=Host(`laravel.docker.localhost`)"
      - "traefik.enable=true"
      - "traefik.http.routers.laravel1.entrypoints=http"
    depends_on:
    - mariadb

  mariadb:
    image: mariadb
    restart: always
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: temp
    ports:
    - "8889:3306"

  composer:
    image: composer:1.9
    command: [ "composer", "install" ]
    volumes:
      - ./src:/app